# Uncomment the next line to define a global platform for your project

target 'NYTimes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 5.0.0-rc.3'
  # Pods for NYTimes

  target 'NYTimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYTimesUITests' do
    # Pods for testing
  end

end
